//The fun and easy project “Guess the Number” is a short Java project that allows the user to guess the number generated by the computer & involves
// the following steps:

//The system generates a random number from a given range, say 1 to 100.
//The user is prompted to enter their given number in a displayed dialogue box.
//The computer then tells if the entered number matches the guesses number or it is higher/lower than the generated number.
//The game continues under the user guessing the number.
//You can also incorporate further details as:

//Limiting the number of attempts.
//Adding more rounds.
//Displaying score.
//Giving points based on the number of attempts.

//CODE:

import java.util.Scanner;
public class Number_Guessing_Game{
    public static void main(String[] args) {
        System.out.println("Try to fetch a Number between 1 and 100, and try to guess a number");
        Scanner sc=new Scanner(System.in);
        boolean playagain;
        do{
            Game();
            System.out.println("Would you like to play the game again? Y/N");
            String playagainstr=sc.next();
            playagain=playagainstr.equalsIgnoreCase("Y");
        }while(playagain);
        System.out.println("Thanks for playing! Thank You");
    }
    static void Game(){
        int Number;
        int GuessedNumber;
        int GuessedCount;

        Number=(int)(100*Math.random())+1;
        GuessedCount=0;
        System.out.println();
        System.out.println("What is the guessed number?");
        Scanner sc1=new Scanner(System.in);
        while(true){
            GuessedNumber=sc1.nextInt();
            GuessedCount++;

            if(GuessedCount==Number)
            {
                System.out.println("You have tried "+GuessedCount+"Guesses!The Number was"+Number);
                break;
            }
            if(GuessedCount==5)
            {
                System.out.println("You ave tried 5 guesses.");
                System.out.println("You lost.The number was "+Number);
                break;
            }
            if(GuessedNumber<Number){
                System.out.println("The number of the guesses you have made are too low.Please try again.");

            }
            else if(GuessedNumber>Number)
            {
                System.out.println("The guesses which you have made are too high.Please try again");
            }
        }
        System.out.println();
    }
}